In [4]:
import numpy as np

In [3]:
def decomposition_LDU(A):
    D=np.diag(np.diag(A))
    U=np.fromfunction(lambda i,j:i<j,A.shape)*A
    L=np.fromfunction(lambda i,j:i>j,A.shape)*A
    return L,D,U

In [5]:
n=5
A=np.random.randint(-6,6,(n,n))
A

array([[-2, -4,  0, -6, -4],
       [-2,  2, -6,  4, -2],
       [-3, -4,  4, -4,  1],
       [ 3, -4,  4,  3, -2],
       [-4,  4,  4, -5, -5]])

In [4]:
decomposition_LDU(A)

(array([[ 0,  0,  0,  0,  0],
        [ 3,  0,  0,  0,  0],
        [ 3,  3,  0,  0,  0],
        [-6,  4, -4,  0,  0],
        [-6,  0,  0, -1,  0]]),
 array([[-3,  0,  0,  0,  0],
        [ 0, -6,  0,  0,  0],
        [ 0,  0, -1,  0,  0],
        [ 0,  0,  0,  4,  0],
        [ 0,  0,  0,  0,  1]]),
 array([[ 0,  2,  5,  1,  4],
        [ 0,  0,  4, -5, -6],
        [ 0,  0,  0,  0,  3],
        [ 0,  0,  0,  0, -2],
        [ 0,  0,  0,  0,  0]]))

# Proposer une fonction calculant "manuellement" le produit de deux matrices

In [5]:
def produit_matriciel(A,B):
    C=np.zeros((A.shape[0],B.shape[1]))
    if A.shape[1]!=B.shape[0] :raise Exception('Forme matrice incorrect')
    for  i in range(A.shape[0]):
        for j in range(B.shape[1]):
            C[i,j]=sum(A[i,k]*B[k,j] for k in range(B.shape[0]))
    return C

In [6]:
A=np.random.randint(-5,5,(3,3))
B=np.random.randint(-5,5,(3,3))

In [7]:
produit_matriciel(A,B),A@B

(array([[11., -3., -9.],
        [ 6., -1., -4.],
        [ 2.,  4., -8.]]),
 array([[11, -3, -9],
        [ 6, -1, -4],
        [ 2,  4, -8]]))

In [8]:
%%timeit
produit_matriciel(A,B)

8.08 µs ± 116 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [9]:
%%timeit
A@B

548 ns ± 1.87 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


# Proposer des fonctions permettant de renvoyer les matrices élémentaire suivantes :

In [10]:
def genere_Tij(n,i,j):
    A=np.eye(n)
    A[[i,j]]=A[[j,i]]
    return A

In [11]:
 genere_Tij(5,2,3)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1.]])

In [12]:
def genere_Diλ(n,i,λ):
    A=np.eye(n)
    A[i]=A[i]*λ
    return A

In [13]:
genere_Diλ(5,2,3)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [9]:
def genere_Lrs_λ(n,r,s,λ):
    A=np.eye(n)
    A[r,s]=λ
    return A

In [15]:
genere_Lrs_λ(5,2,3,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 5., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# Vérifiez sur quelques exemples les informations données en cours concernant les matrices inverses des matrices précédentes.

In [16]:
genere_Tij(5,2,3)@genere_Tij(5,2,3)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Tij ⇔ Tij Tij = I

In [17]:
genere_Diλ(5,2,3)@genere_Diλ(5,2,1/3)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# Dr(λ)Dr( 1/λ )=I

In [18]:
genere_Lrs_λ(5,2,3,5)@genere_Lrs_λ(5,2,3,-5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# Lrs(λ)Lrs(−λ) = I

# Vérifiez que le produit A=Lr1,s(λ1)Lr2,s(λ2) donne une matrice identité à laquelle on ajoute λ1 sur Ar1,s et λ2 sur Ar2,s.

In [19]:
A=genere_Lrs_λ(5,2,3,5)@genere_Lrs_λ(5,4,3,2)


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 5., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 2., 1.]])

# Proposez deux écritures de génération de la matrice Mr((λr+1,…,λn))=Lr+1,r(λr+1)…Ln,r(λn).

In [8]:
def generation_M_first_way(A,r):
    M=np.eye(len(A))
    M[r+1:,r]=-A[r+1:,r]/A[r,r]
    return M

In [5]:
A=np.random.randint(-5,5,(5,5))

In [48]:
A

array([[-2, -2,  4,  2,  2],
       [ 2,  0, -3, -4, -5],
       [-5,  2,  1,  0,  0],
       [ 1, -2, -2, -4, -1],
       [ 2, -2, -4,  0, -3]])

In [12]:
generation_M_first_way(A,1)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  2.,  1.,  0.,  0.],
       [ 0.,  2.,  0.,  1.,  0.],
       [ 0., -2.,  0.,  0.,  1.]])

In [14]:
A

array([[-2, -4,  0, -6, -4],
       [-2,  2, -6,  4, -2],
       [-3, -4,  4, -4,  1],
       [ 3, -4,  4,  3, -2],
       [-4,  4,  4, -5, -5]])

In [10]:
def generation_M_second_way(A,r):
    n=len(A)
    M=np.eye(n)
    Minverse=np.eye(n)
    for i in range(r+1,n):
        M=M @ genere_Lrs_λ(n,i,r,-A[i,r]/A[r,r])
        Minverse=Minverse @ genere_Lrs_λ(n,i,r,A[i,r]/A[r,r])
    return M,Minverse

In [17]:
generation_M_second_way(A,3)

(array([[1.        , 0.        , 0.        , 0.        , 0.        ],
        [0.        , 1.        , 0.        , 0.        , 0.        ],
        [0.        , 0.        , 1.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        , 1.        , 0.        ],
        [0.        , 0.        , 0.        , 1.66666667, 1.        ]]),
 array([[ 1.        ,  0.        ,  0.        ,  0.        ,  0.        ],
        [ 0.        ,  1.        ,  0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  1.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  1.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        , -1.66666667,  1.        ]]))