In [1]:
import numpy as np

In [39]:
def decomposition_LDU(A):
    D=np.diag(np.diag(A))
    U=np.fromfunction(lambda i,j:i<j,A.shape)*A
    L=np.fromfunction(lambda i,j:i>j,A.shape)*A
    return L,D,U

In [34]:
n=5
A=np.random.randint(-6,6,(n,n))
A

array([[ 4,  2,  1, -5, -1],
       [ 0,  2, -5, -3,  0],
       [-6,  3,  4, -6, -1],
       [ 2,  5, -2,  3, -1],
       [ 4,  1, -3, -6,  3]])

In [40]:
decomposition_LDU(A)

(array([[ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0],
        [-6,  3,  0,  0,  0],
        [ 2,  5, -2,  0,  0],
        [ 4,  1, -3, -6,  0]]),
 array([[4, 0, 0, 0, 0],
        [0, 2, 0, 0, 0],
        [0, 0, 4, 0, 0],
        [0, 0, 0, 3, 0],
        [0, 0, 0, 0, 3]]),
 array([[ 0,  2,  1, -5, -1],
        [ 0,  0, -5, -3,  0],
        [ 0,  0,  0, -6, -1],
        [ 0,  0,  0,  0, -1],
        [ 0,  0,  0,  0,  0]]))

# Proposer une fonction calculant "manuellement" le produit de deux matrices

In [90]:
def produit_matriciel(A,B):
    C=np.zeros((A.shape[0],B.shape[1]))
    if A.shape[1]!=B.shape[0] :raise Exception('Forme matrice incorrect')
    for  i in range(A.shape[0]):
        for j in range(B.shape[1]):
            C[i,j]=sum(A[i,k]*B[k,j] for k in range(B.shape[0]))
    return C

In [83]:
A=np.random.randint(-5,5,(3,3))
B=np.random.randint(-5,5,(3,3))

In [92]:
produit_matriciel(A,B),A@B

(array([[ 28.,   5.,   0.],
        [ 16.,  35.,  12.],
        [-12.,  -6.,   9.]]),
 array([[ 28,   5,   0],
        [ 16,  35,  12],
        [-12,  -6,   9]]))

In [93]:
%%timeit
produit_matriciel(A,B)

7.96 µs ± 101 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [94]:
%%timeit
A@B

551 ns ± 8.38 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


# Proposer des fonctions permettant de renvoyer les matrices élémentaire suivantes :

In [97]:
def genere_Tij(n,i,j):
    A=np.eye(n)
    A[[i,j]]=A[[j,i]]
    return A

In [98]:
 genere_Tij(5,2,3)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1.]])

In [104]:
def genere_Diλ(n,i,λ):
    A=np.eye(n)
    A[i]=A[i]*λ
    return A

In [106]:
genere_Diλ(5,2,3)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [107]:
def genere_Lrs_λ(n,r,s,λ):
    A=np.eye(n)
    A[r,s]=λ
    return A

In [110]:
genere_Lrs_λ(5,2,3,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 5., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# Vérifiez sur quelques exemples les informations données en cours concernant les matrices inverses des matrices précédentes.

In [114]:
genere_Tij(5,2,3)@genere_Tij(5,2,3)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Tij ⇔ Tij Tij = I

In [115]:
genere_Diλ(5,2,3)@genere_Diλ(5,2,1/3)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# Dr(λ)Dr( 1/λ )=I

In [116]:
genere_Lrs_λ(5,2,3,5)@genere_Lrs_λ(5,2,3,-5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# Lrs(λ)Lrs(−λ) = I

# Vérifiez que le produit A=Lr1,s(λ1)Lr2,s(λ2) donne une matrice identité à laquelle on ajoute λ1 sur Ar1,s et λ2 sur Ar2,s.

In [118]:
A=genere_Lrs_λ(5,2,3,5)@genere_Lrs_λ(5,4,3,2)
A

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 5., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 2., 1.]])

# Proposez deux écritures de génération de la matrice Mr((λr+1,…,λn))=Lr+1,r(λr+1)…Ln,r(λn).

# TP SUIVANT

In [112]:
def M(A,s):
    n=A.shape[0]
    I=np.eye(n)
    I[s+1:,s]=-A[s+1:,s]/A[s,s]
    return I

for s in range(n-1):
    A=M(A,s)@A
    print(A)