In [125]:
import numpy as np
import scipy.linalg as sc
import warnings
warnings.filterwarnings("ignore")

Résolution de Ax=b avec A une matrice carrée n×n et b∈Rn

    Résolution d'un système linéaire triangulaire
        supérieur
        inférieur
    Méthode de Gauss
        Méthode de triangulation de Gauss
        Appel à la résolution
    Résolution par décomposition LU
        Décomposition LU de la matrice A
        Résolution du système initial par la résolution de deux système triangulaires (supérieur et inférieur)
    Méthodes itératives
    Si vous avez le temps, vous écrirez les méthodes par calcul des éléments de xi

    et également l'écriture matricielle.
        Méthode de Jabobi
        Méthode de Gauss-Seidel
        Méthode de relaxation

Implantez la méthode du calcul de l'inverse d'une matrice carrée A
par "double triangulation", puis division des lignes par les éléments diagonaux.

In [127]:
def genere_Tij(n,i,j):
    A=np.eye(n)
    A[[i,j]]=A[[j,i]]
    return A

In [129]:
def genere_Lrs_λ(n,r,s,λ):
    A=np.eye(n)
    A[r,s]def generation_M_first_way(A,r):
    M=np.eye(len(A))
    M[r+1:,r]=-A[r+1:,r]/A[r,r]
    return M=λ
    return A

In [130]:
def generation_M_first_way(A,r):
    M=np.eye(len(A))
    M[r+1:,r]=-A[r+1:,r]/A[r,r]
    return M

## 1) Résolution de Ax=b avec A une matrice carrée n×n et b∈Rn

## Résolution d'un système linéaire triangulaire

In [100]:
def resol_superieur(A,b):
    n=A.shape[0]
    x=np.zeros(n)
    n=n-1
    x[n]=b[n]/A[n,n]
    for i in range(n-1,-1,-1):
        x[i]=(b[i]-sum(A[i,i+1:]*x[i+1:]))/A[i,i]
    return x

In [59]:
A=np.random.randint(1,6,(3,3))

In [73]:
l,u=sc.decomp_lu.lu(A)[1:3]
u

array([[5.   , 2.   , 3.   ],
       [0.   , 3.2  , 2.8  ],
       [0.   , 0.   , 1.625]])

In [101]:
resol_superieur(u,np.array([1,1,-2]))

array([ 0.38269231,  1.38942308, -1.23076923])

In [122]:
u@np.array([ 0.38269231,  1.38942308, -1.23076923])

array([ 1.00000002,  1.00000001, -2.        ])

In [119]:
def resol_inferieur(A,b):
    n=A.shape[0]
    x=np.zeros(n)
    x[0]=b[0]/A[0,0]
    for i in range(1,n):
        x[i]=(b[i]-sum(A[i,0:i]*x[0:i]))/A[i,i]
    return x

In [120]:
resol_inferieur(l,np.array([1,1,-2]))

array([ 1.    ,  0.6   , -2.9375])

In [121]:
l@np.array([ 1.,0.6, -2.9375])

array([ 1.,  1., -2.])

In [201]:
A

array([[2, 4, 4],
       [3, 3, 5],
       [5, 2, 3]])

In [202]:
A2=A.copy()

# Méthode de Gauss

In [214]:
def triangulation_de_Gauss(A,b):
    for i in range(A.shape[1]-1):
        max=np.argmax(A[i:,i])+1+i
        if A[max,i]>A[i,i]:
             A=genere_Tij(A.shape[0],max,i)@A
             b=genere_Tij(b.shape[0],max,i)@b
        A=generation_M_first_way(A,i)@A
        b=generation_M_first_way(A,i)@b
    return A,b

In [213]:
triangulation_de_Gauss(A,np.array([1,2,3]))

IndexError: index 3 is out of bounds for axis 0 with size 3

In [209]:
def resolution_de_Gauss(A,b):
    return resol_superieur(A,b)

In [210]:
a,c=triangulation_de_Gauss(A,np.array([1,2,3]))
resolution_de_Gauss(a,c)

array([ 0.11709402,  1.72649573, -0.34615385])

In [211]:
A2@np.array([ 0.11709402,  1.72649573, -0.34615385])

array([5.75555556, 3.8       , 3.00000001])

In [44]:
def M(A,s):
    n=A.shape[0]
    I=np.eye(n)
    I[s+1:,s]=-A[s+1:,s]/A[s,s]
    return I
for s in range(n-1):
    A=M(A,s)@A
    print(A)

NameError: name 'n' is not defined